language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  except:
    - /^((release|hotfix)\/)?\d\.\d/
    - /^(feature|bugfix)\//

install:
  - composer install --no-dev

script: phpunit --configuration phpunit.xml.dist --coverage-text

after_success:
  - bash <(curl -s https://codecov.io/bash)